export interface InstructorProfile {
  id: string;
  name: string;
  title: string;
  avatarUrl: string;
  rating: number;
  reviewCount: number;
  experienceYears: number;
  qualifications: string[];
  hourlyRate1on1: number;
  hourlyRateGroup: number;
  location: string;
  bio: string;
  lessonTypes: ('1-on-1' | 'Group Coaching' | 'Sparring Partner' | 'Academy Clinic')[];
  availableSlots: string[];
}

export interface LearnSport {
  id: string;
  name: string;
  icon: string;
  tagline: string;
  description: string;
  imageUrl: string;
  category: 'racket' | 'team' | 'combat';
  availableInstructorsCount: number;
  minPrice: number;
  popularTopics: string[];
  instructors: InstructorProfile[];
}

export const LEARN_SPORTS: LearnSport[] = [
  {
    id: 'boxing',
    name: 'Boxing',
    icon: '🥊',
    tagline: 'Ring Strategy, Sparring & Technical Defense',
    description: 'Master stance, footwork, jab combos, defensive slips, and high-intensity boxing conditioning with pro fighter coaches.',
    imageUrl: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1200&q=80',
    category: 'combat',
    availableInstructorsCount: 8,
    minPrice: 50,
    popularTopics: ['Heavy Bag Drills', 'Sparring Technique', 'Footwork & Speed', 'Counter Punching'],
    instructors: [
      {
        id: 'box-1',
        name: 'Gia Beridze',
        title: 'National Boxing Champion & Senior Sparring Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        rating: 4.9,
        reviewCount: 42,
        experienceYears: 12,
        qualifications: ['AIBA Certified Coach', 'Georgian National Champ', 'Pro Sparring Instructor'],
        hourlyRate1on1: 65,
        hourlyRateGroup: 35,
        location: 'Champions Boxing Gym, Vera',
        bio: 'Ex-national team boxer specializing in sharp footwork, defensive head movement, and customized heavy bag workouts.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Sparring Partner'],
        availableSlots: ['Mon 10:00 AM', 'Mon 04:00 PM', 'Wed 11:00 AM', 'Fri 06:00 PM', 'Sat 02:00 PM'],
      },
      {
        id: 'box-2',
        name: 'Nino Javakhishvili',
        title: 'Functional Boxing & Conditioning Trainer',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
        rating: 4.8,
        reviewCount: 29,
        experienceYears: 7,
        qualifications: ['Master of Sports', 'HIIT Boxing Specialist', 'Cardio Sparring License'],
        hourlyRate1on1: 50,
        hourlyRateGroup: 30,
        location: 'Saburtalo Boxing Center',
        bio: 'Passionate coach focusing on core strength, combination speed, mitt work, and accessible entry for beginners.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Academy Clinic'],
        availableSlots: ['Tue 09:00 AM', 'Thu 05:00 PM', 'Fri 07:00 PM', 'Sun 11:00 AM'],
      },
    ],
  },
  {
    id: 'tennis',
    name: 'Tennis',
    icon: '🎾',
    tagline: 'Precision Strokes, Serve & Court Movement',
    description: 'Elevate your forehand, backhand topspin, service power, and tactical match strategy on clay and hard courts.',
    imageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=1200&q=80',
    category: 'racket',
    availableInstructorsCount: 14,
    minPrice: 60,
    popularTopics: ['Kick & Slice Serve', 'Forehand Topspin', 'Baseline Rallying', 'Net Volley Drills'],
    instructors: [
      {
        id: 'ten-1',
        name: 'Luka Kapanadze',
        title: 'Former ATP Player & PTR Master Professional',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        rating: 5.0,
        reviewCount: 64,
        experienceYears: 15,
        qualifications: ['PTR Master Professional', 'Ex-ATP Top 400', 'ITF Level 3 Head Coach'],
        hourlyRate1on1: 85,
        hourlyRateGroup: 45,
        location: 'Leila Meskhi Tennis Academy, Marjanishvili',
        bio: 'Dedicated to refining technical biomechanics, court geometry awareness, and competitive match mental toughness.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Sparring Partner'],
        availableSlots: ['Mon 08:00 AM', 'Tue 06:00 PM', 'Thu 07:00 AM', 'Fri 05:00 PM', 'Sat 10:00 AM'],
      },
      {
        id: 'ten-2',
        name: 'Ana Gelashvili',
        title: 'High-Performance Junior & Adult Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
        rating: 4.9,
        reviewCount: 38,
        experienceYears: 9,
        qualifications: ['PTR Certified Professional', 'B.S. Sports Science', 'Georgian Junior National Coach'],
        hourlyRate1on1: 65,
        hourlyRateGroup: 35,
        location: 'Mziuri Park Tennis Courts, Vake',
        bio: 'Specialist in rapid stroke progression, footwork drills, and friendly hitting lessons for intermediate players.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Academy Clinic'],
        availableSlots: ['Wed 10:00 AM', 'Thu 04:00 PM', 'Sat 03:00 PM', 'Sun 09:00 AM'],
      },
    ],
  },
  {
    id: 'padel',
    name: 'Padel',
    icon: '🏓',
    tagline: 'Wall Rebounds, Bandeja Shots & Doubles Tactics',
    description: 'Master glass wall defense, position play, lob timing, and aggressive net vibora strikes in fast-paced Padel matches.',
    imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=1200&q=80',
    category: 'racket',
    availableInstructorsCount: 9,
    minPrice: 55,
    popularTopics: ['Bandeja & Chiquita Shots', 'Glass Wall Defence', 'Doubles Position Switching', 'Net Control'],
    instructors: [
      {
        id: 'pad-1',
        name: 'Mateo Rossi',
        title: 'FIP Certified Padel Head Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
        rating: 4.9,
        reviewCount: 51,
        experienceYears: 10,
        qualifications: ['FIP International Coach', 'Spanish Padel Federation Certified', 'Tbilisi Padel Open Champ'],
        hourlyRate1on1: 75,
        hourlyRateGroup: 40,
        location: 'Vake Padel Arena & Lisi Courts',
        bio: 'Brings authentic Spanish padel methodology to Georgia. Learn how to use the walls as your ultimate weapon.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Sparring Partner', 'Academy Clinic'],
        availableSlots: ['Mon 05:00 PM', 'Wed 07:00 PM', 'Fri 08:00 AM', 'Sat 11:00 AM', 'Sun 04:00 PM'],
      },
      {
        id: 'pad-2',
        name: 'David Chikovani',
        title: 'Padel Tactics & Group Master Instructor',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
        rating: 4.8,
        reviewCount: 33,
        experienceYears: 6,
        qualifications: ['Certified Padel Trainer', 'National Tour Finalist'],
        hourlyRate1on1: 55,
        hourlyRateGroup: 30,
        location: 'Olympic Padel Center, Saburtalo',
        bio: 'Focuses on team communication, wall positioning, smooth transitions from defense to attack, and fun group clinics.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Academy Clinic'],
        availableSlots: ['Tue 11:00 AM', 'Thu 06:00 PM', 'Sat 01:00 PM', 'Sun 02:00 PM'],
      },
    ],
  },
  {
    id: 'football',
    name: 'Football',
    icon: '⚽',
    tagline: 'Technical Control, Tactical Passing & Agility',
    description: 'Sharpen ball mastery, first touch, tactical movement, long-range shooting, and match positioning on turf pitches.',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80',
    category: 'team',
    availableInstructorsCount: 18,
    minPrice: 45,
    popularTopics: ['First Touch Control', '1v1 Dribbling Mastery', 'Striking Technique', 'Tactical Positioning'],
    instructors: [
      {
        id: 'fut-1',
        name: 'Tornike Shengelia',
        title: 'UEFA A Licensed Football Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
        rating: 4.9,
        reviewCount: 78,
        experienceYears: 14,
        qualifications: ['UEFA A License', 'Ex-Dinamo Tbilisi Academy Coach', 'Sports Performance Specialist'],
        hourlyRate1on1: 70,
        hourlyRateGroup: 35,
        location: 'Inter Academy Fields, Digomi',
        bio: 'Focused on modern tactical awareness, high-speed decision making, body orientation, and technical execution under pressure.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Academy Clinic'],
        availableSlots: ['Mon 04:00 PM', 'Wed 05:00 PM', 'Thu 08:00 AM', 'Sat 09:00 AM', 'Sun 05:00 PM'],
      },
      {
        id: 'fut-2',
        name: 'Beka Tsereteli',
        title: 'Youth & Amateur Skill Development Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
        rating: 4.8,
        reviewCount: 45,
        experienceYears: 8,
        qualifications: ['UEFA B License', 'Youth Academy Trainer', 'Coerver Coaching Certified'],
        hourlyRate1on1: 50,
        hourlyRateGroup: 25,
        location: 'Marakana Arena, Saburtalo',
        bio: 'Specializes in Coerver ball mastery, quick footwork ladders, shooting accuracy drills, and 5v5 game positioning.',
        lessonTypes: ['1-on-1', 'Group Coaching'],
        availableSlots: ['Tue 05:00 PM', 'Thu 04:00 PM', 'Fri 06:00 PM', 'Sat 02:00 PM'],
      },
    ],
  },
  {
    id: 'rugby',
    name: 'Rugby',
    icon: '🏉',
    tagline: 'Tackling Mechanics, Passing & Lineout Execution',
    description: 'Learn dynamic rugby passing, safe contact & tackling technique, scrum positioning, and endurance conditioning.',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80',
    category: 'team',
    availableInstructorsCount: 6,
    minPrice: 50,
    popularTopics: ['Safe Contact & Tackling', 'Spin & Pop Passing', 'Scrum & Ruck Fundamentals', 'Match Conditioning'],
    instructors: [
      {
        id: 'rug-1',
        name: 'Vano Lomidze',
        title: 'Georgian National Rugby Squad Alumni & Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
        rating: 5.0,
        reviewCount: 31,
        experienceYears: 16,
        qualifications: ['World Rugby Level 2 Coach', 'Ex-Lelo Saracens Player', 'Strength & Conditioning Specialist'],
        hourlyRate1on1: 75,
        hourlyRateGroup: 40,
        location: 'Shevardeni Rugby Stadium, Bagebi',
        bio: 'Teaches world-class rugby fundamentals with strict attention to safe contact technique, breakdown power, and strategic teamwork.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Academy Clinic'],
        availableSlots: ['Tue 04:00 PM', 'Thu 06:00 PM', 'Sat 10:00 AM', 'Sun 03:00 PM'],
      },
    ],
  },
  {
    id: 'basketball',
    name: 'Basketball',
    icon: '🏀',
    tagline: 'Shooting Form, Handles & Defensive Footwork',
    description: 'Build an unguardable jumper, sharp crossovers, court vision, post moves, and lockdown perimeter defense.',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80',
    category: 'team',
    availableInstructorsCount: 11,
    minPrice: 50,
    popularTopics: ['Jump Shot Mechanics', 'Crossover & Handle Drills', 'Pick & Roll IQ', 'Explosive Vertical Jump'],
    instructors: [
      {
        id: 'bas-1',
        name: 'Irakli Gogidze',
        title: 'Pro Basketball Skill Trainer & Shooting Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
        rating: 4.9,
        reviewCount: 56,
        experienceYears: 11,
        qualifications: ['FIBA Certified Coach', 'Ex-Superleague Guard', "I'm Possible Training Certified"],
        hourlyRate1on1: 65,
        hourlyRateGroup: 35,
        location: 'Zaza Pachulia Academy & Brooklyn Hall',
        bio: 'Transform your shooting mechanics and ball-handling fluidness through detailed video breakdown and high-rep skill drills.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Academy Clinic'],
        availableSlots: ['Mon 09:00 AM', 'Wed 06:00 PM', 'Fri 05:00 PM', 'Sat 12:00 PM', 'Sun 10:00 AM'],
      },
    ],
  },
  {
    id: 'volleyball',
    name: 'Volleyball',
    icon: '🏐',
    tagline: 'Overhead Setting, Spiking Power & Serve Precision',
    description: 'Perfect your approach jump, spiking wrist snap, setting touch, jump float serve, and beach court agility.',
    imageUrl: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1200&q=80',
    category: 'team',
    availableInstructorsCount: 7,
    minPrice: 45,
    popularTopics: ['Spike Timing & Snap', 'Overhead Setting Accuracy', 'Jump Float Serve', 'Beach Dig & Movement'],
    instructors: [
      {
        id: 'vol-1',
        name: 'Elena Dolidze',
        title: 'National Volleyball Master Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
        rating: 4.9,
        reviewCount: 39,
        experienceYears: 10,
        qualifications: ['FIVB Level 2 Coach', 'National Beach Tour Champion', 'Biomechanics Instructor'],
        hourlyRate1on1: 60,
        hourlyRateGroup: 30,
        location: 'Digomi Olympic Arena & Vake Courts',
        bio: 'Specializing in spike approach footwork, clean setting technique, and dynamic court communication for indoor & beach volleyball.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Academy Clinic'],
        availableSlots: ['Mon 11:00 AM', 'Wed 04:00 PM', 'Fri 06:00 PM', 'Sat 04:00 PM'],
      },
    ],
  },
  {
    id: 'badminton',
    name: 'Badminton',
    icon: '🏸',
    tagline: 'High Clears, Drop Shots & Rapid Footwork',
    description: 'Develop lightning-fast reflex speed, precise wrist snaps, steep smash angles, and deceptive drop shots.',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80',
    category: 'racket',
    availableInstructorsCount: 5,
    minPrice: 45,
    popularTopics: ['Jump Smash Power', 'Net Deception & Drops', 'Footwork Split-step', 'Doubles Rotations'],
    instructors: [
      {
        id: 'bad-1',
        name: 'Giga Meladze',
        title: 'BWF Certified Badminton Instructor',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
        rating: 4.8,
        reviewCount: 22,
        experienceYears: 8,
        qualifications: ['BWF Level 1 Coach', 'National Tournament Winner'],
        hourlyRate1on1: 55,
        hourlyRateGroup: 30,
        location: 'Central Badminton Complex, Isani',
        bio: 'Focuses on split-step footwork timing, racquet wrist speed, and stamina drills for competitive players.',
        lessonTypes: ['1-on-1', 'Group Coaching'],
        availableSlots: ['Tue 10:00 AM', 'Thu 03:00 PM', 'Sat 02:00 PM'],
      },
    ],
  },
  {
    id: 'tabletennis',
    name: 'Table Tennis',
    icon: '🏓',
    tagline: 'Spin Control, Loop Drives & Reaction Drills',
    description: 'Master topspin loops, backspin chop defense, serve spin variation, and high-speed table placement.',
    imageUrl: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?auto=format&fit=crop&w=1200&q=80',
    category: 'racket',
    availableInstructorsCount: 6,
    minPrice: 40,
    popularTopics: ['Topspin Loop Drive', 'Heavy Backspin Push', 'Deceptive Pendulum Serve', 'Reaction Speed'],
    instructors: [
      {
        id: 'tt-1',
        name: 'Soso Pantsulaia',
        title: 'ITTF Level 2 Master Coach',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
        rating: 4.9,
        reviewCount: 47,
        experienceYears: 13,
        qualifications: ['ITTF Certified Coach', 'Multiple National Gold Medalist'],
        hourlyRate1on1: 50,
        hourlyRateGroup: 25,
        location: 'Tbilisi Table Tennis Club, Vera Park',
        bio: 'Learn how to read opponents spin instantly, develop explosive forehand loops, and serve unreturnable balls.',
        lessonTypes: ['1-on-1', 'Group Coaching', 'Sparring Partner'],
        availableSlots: ['Mon 02:00 PM', 'Wed 05:00 PM', 'Fri 04:00 PM', 'Sun 12:00 PM'],
      },
    ],
  },
];

export function getLearnSportById(id: string): LearnSport | undefined {
  return LEARN_SPORTS.find((sport) => sport.id === id.toLowerCase());
}
